### ISSUE TITLE
Fizzbuzz 구현

### ISSUE THREAD

**Issue by jaeseong-kang** [FC-Team-6/team-fizzbuzz#1]
## Description

fizzbuzz를 구현하겠습니다.
1부터 20까지 정수에 대해
3의 배수라면, fizz
5의 배수라면, buzz
15의 배수라면, fizzbuzz
그렇지 않은 모든 경우에는 숫자 그대로를 출력한다.

## Task

- [ ] Print fizz
- [ ] Print buzz
- [ ] Print fizzbuzz
- [ ] Print number

## References

- [Link Text](Link URL)

**Comment by JJJJiwon** [comment]
대단합니다..근데 저는 뭘 해야 하죠....ㅋㅋㅋ
